version: '3.8'
services:
  mariadb:
    image: mariadb:10.11
    container_name: lab_mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: mysqlroot
      MARIADB_DATABASE: labdb
      MARIADB_USER: dba_user
      MARIADB_PASSWORD: dbapass
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/lab.cnf
      - ./logs/mysql:/var/log/mysql
      - ./mysql/init/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-pmysqlroot"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  postgres:
    image: postgres:16
    container_name: lab_postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pgroot
      POSTGRES_DB: labdb
      POSTGRES_USER: dba_user
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./logs/postgres:/var/log/postgresql
      - ./postgres/init/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dba_user -d labdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data:
  pg_data: